### ISSUE TITLE
Request for position: aligning on <link rel=prefetch>

### ISSUE THREAD

**Issue by noamr** [WebKit/standards-positions#114]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: Prefetch processing model
* Spec URL:  https://github.com/whatwg/html/pull/8111
* GitHub repository: https://github.com/whatwg
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): 

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/723

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=194539
* Radar: rdar://problem/3176096

### Anything else we need to know

Some details in the proposal to align over:
- Prefetch is essentially designed to populate the HTTP cache at low priority, for subsequent navigations and resource loads.
- The `Accept` header for prefetch is defined as the same one that is sent with frame navigation. This prevents double-prefetches with `Vary: Accept`. See https://github.com/whatwg/fetch/pull/1485
- Sending `Sec-Purpose` for prefetches, to allow servers to discern between regular requests and resource hints. See https://github.com/whatwg/fetch/pull/1576
- Using "least restrictive" CSP directive. See https://github.com/w3c/webappsec-csp/pull/582

**Comment by othermaciej** [comment]
Defining how prefetch works with http cache partitioning (in a way that is not a privacy violation and does not result in duplicate loads) is a hard blocker for us supporting it. The issue is described at https://github.com/w3c/resource-hints/issues/82 but remains unfixed. Current plan seems to be to address this as part of a larger rewrite: https://github.com/w3c/resource-hints/issues/86#issuecomment-1050638000 but that seems to be stalled.

Without spec text addressing this it’s hard for us to meaningfully evaluate this since the current spec only allows either enabling tracking or making prefetches useless.

**Comment by domenic** [comment]
Yes, I'd really urge WebKit to pay attention to the difference between subresource prefetch (this issue, and the linked spec therein) which is totally unproblematic, and navigational prefetch (#54, and the linked spec therein) which requires more care. In both cases, we think we've done the work! But please evaluate the work, instead of assuming what's designed is non-private or that the spec text is lacking.

**Comment by noamr** [comment]
Added a [comment](https://github.com/w3c/resource-hints/issues/82#issuecomment-1368776115) in the linked spec issue. @annevk, I'm confused as this is different from what you said [here](https://github.com/whatwg/html/pull/8111#pullrequestreview-1126322782). I feel there's some misunderstanding here, would you be able to help?

**Comment by annevk** [comment]
Yeah, I think this is an acceptable model.

To elaborate, the HTML PR does not define its own cache and relies completely on the fetch algorithm. That algorithm takes care of partitioning all network state. As such prefetches will only be useful if they end up being hit in the same partition by a regular fetch later on.

I chatted with Maciej and he agreed, so I’ll resolve this as “position: support” seven days from now.

**Comment by othermaciej** [comment]
I agree with Anne. I previously was confused about the state of the discussion; it seems like the HTML PR supersedes those older PRs and issues that I linked to.

It seems like the new design will not violate partitioning, so that's from a privacy POV. It will make `<link rel=prefetch>` useless for navigation prefetch, but Anne says we have indications that this would not lead to significant wasteful double-fetches.

**Comment by noamr** [comment]
> I agree with Anne. I previously was confused about the state of the discussion; it seems like the HTML PR supersedes those older PRs and issues that I linked to.
> 
> It seems like the new design will not violate partitioning, so that's from a privacy POV. It will make `<link rel=prefetch>` useless for navigation prefetch, but Anne says we have indications that this would not lead to significant wasteful double-fetches.

Thanks for re-reviewing! Small correction: `<link rel=prefetch>` useless for cross-origin/cross-site navigation prefetch (depending on partitioned cache etc), but is totally OK for same-origin navigational prefetch.

**Comment by othermaciej** [comment]
> To reiterate from the WebKit issue, as someone making a library ([instant.page](https://instant.page/)) that uses navigational prefetch, I know it would be totally fine if Safari implemented only same-origin navigational prefetch and cross-origin navigational prefetch was a noop.

I'm not sure this is possible. Can cross-site navigational prefetch be distinguished from cross-site subframe resource prefetch?

**Comment by dieulot** [comment]
My message was about “unlocking” WebKit/Safari’s implementation — a case against spec compliance purity. It’s a response to Maciej’s third paragraph in [webkit.org/b/194539#c10](https://bugs.webkit.org/show_bug.cgi?id=194539#c10).

> Can cross-site navigational prefetch be distinguished from cross-site subframe resource prefetch?

Now that the `as` attribute is officially no more, it turns out no distinction between any type of intended usage can be made.
Even so, shipping same-origin prefetch only, for any type of content, would be beneficial — if interaction with cache partitioning is still a large part what is blocking WebKit.

**Comment by hober** [comment]
Closing as we've identified our position.
