### ISSUE TITLE
CSS Cascading and Inheritance Level 6 (@scope)

### ISSUE THREAD

**Issue by andruud** [WebKit/standards-positions#13]
## Request for position on an emerging web specification

* WebKittens who can provide input: @anttijk

### Information about the spec

* Spec Title: CSS Cascading and Inheritance Level 6 (`@scope`)
* Spec URL: https://drafts.csswg.org/css-cascade-6/#scope-atrule
* GitHub repository: https://github.com/w3c/csswg-drafts/labels/css-cascade-6
* Explainer (if not README.md in the repository): https://css.oddbird.net/scope/explainer/

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/593
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/625

### Bugs tracking this feature

* WebKit Bugzilla: N/A
* Radar: N/A

### Anything else we need to know

This RFP covers the [@scope rule](https://drafts.csswg.org/css-cascade-6/#scope-atrule) only, not the [new combinator](https://drafts.csswg.org/css-cascade-6/#scope-combinator) nor the [new notation](https://drafts.csswg.org/css-cascade-6/#selector-scoping).

**Comment by hober** [comment]
cc @jensimmons

**Comment by jensimmons** [comment]
This will be incredibly useful for web developers, especially those creating "components" and delivering those components using some kind of JS framework. 

Often such solutions organize the CSS for each component in separate files, and load those files in random order — making it impossible to rely on the cascade for sorting out which rules are applied. `@scope` would allow developers on such projects to scope their CSS to each component. 

Scope is also part of a larger effort to modernize the CSS Cascade — an effort that includes Cascade Layers, Nesting, and Container Queries. Together, these tools will radically change how tech leads architect CSS to meet the demands of today's large-team, multi-year projects. Developers need all four.

**Comment by annevk** [comment]
Given @jensimmons's comment I suggest we mark this as support seven days from now.

**Comment by bramus** [comment]
@annevk Do you have an updated on this? It’s been past 7 days since you replied _“I suggest we mark this as support seven days from now.”_, which would mean that the label https://github.com/WebKit/standards-positions/labels/position%3A%20support can be added? Or are there any blockers/concerns that should be discussed _(within the CSSWG, maybe)_?

If support is expressed, is it for only the `@scope` part _(as per OP’s FRP)_ or does it also included support for the [scoped descendant combinator](https://drafts.csswg.org/css-cascade-6/#scope-combinator) and the [selector notation](https://drafts.csswg.org/css-cascade-6/#selector-scoping)?

**Comment by annevk** [comment]
Thanks for the reminder! The scope of each standards-positions issue is determined by OP.

**Comment by bramus** [comment]
Perfect, thank you.

**Comment by hober** [comment]
Closing as we've identified our position.
