### ISSUE TITLE
Removing the zoom CSS property

### ISSUE THREAD

**Issue by chrishtr** [WebKit/standards-positions#170]
### WebKittens

@smfr

### Title of the spec

Removing the zoom CSS property

### URL to the spec

https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

### Issue Tracker URL

https://github.com/w3c/csswg-drafts/issues/5623

### Description

Chromium intends to remove support for the non-standard zoom CSS property. This request for a standard position is to see if WebKit is willing to do so as well. The CSSWG [does not wish](https://github.com/w3c/csswg-drafts/issues/5623) to standardize this legacy property.

**Comment by chrishtr** [comment]
See also https://bugs.chromium.org/p/chromium/issues/detail?id=1142663

**Comment by smfr** [comment]
It's going to be hard to judge the compat risk, especially interactions with Command-+ style zooming.

**Comment by karlcow** [comment]
I need to talk about the compat risks in general.

**Comment by othermaciej** [comment]
This is a summary of the CSS WG’s decision not to spec `zoom` from the issue:
> @SNDST00M The way zoom currently works is probably now required for web compatibility - we can’t improve the way it works without breaking pages that rely on its current behavior. And its current behavior is too weird and inconsistent to standardize and recommend for implementation.

It seems unlikely that changing the behavior would be unacceptable for web compatibility, yet removing it entirely is fine. The linked bug suggests instead implementing `-moz-transform`, but (a) that’s also nonstandard, so what is gained? And (b) it surely doesn’t have all the behavior quirks of `zoom`, which seemingly undermines the argument that it’s impossible to change `zoom`.

Can someone explain why dropping `zoom` is a good plan even in light of the above?

**Comment by emilio** [comment]
> It's going to be hard to judge the compat risk, especially interactions with Command-+ style zooming.

How so? I thought that Command-+ effectively increased the DPI. Does WebKit implement Command-+ in terms of CSS zoom? How does that work when CSS zoom is actually used? That's a bit surprising but...

**Comment by emilio** [comment]
> The linked bug suggests instead implementing `-moz-transform`, but (a) that’s also nonstandard, so what is gained?

`-moz-transform` is just a parse-time alias to `transform` (much like `-webkit-transform`). That has well-defined behavior (just the `transform` behavior), while `zoom` has all sorts of weird quirks and general undefinedness in presence of new CSS features.

> And (b) it surely doesn’t have all the behavior quirks of `zoom`, which seemingly undermines the argument that it’s impossible to change `zoom`.

Well, not really, the issue here is that back when transforms weren't interoperably supported, authors have used a combination of `-moz-transform` (plus `-moz-transform-origin`) and `zoom` to implement this behavior for Firefox and IE+WebKit, effectively.

If that was the only kind of `zoom` usage, you could think that you could then implement `zoom` as a regular transform-like property (with `transform-origin` implicitly at `0 0` or so), and you'd be right.

But that really doesn't work, because `zoom: 0` and `zoom: 1` are effectively no-op but super-common (because it was a way of getting `display: inline-block`-like behavior in IE), and _not_ used along `-moz-transform`. So those can't really have the transform side-effects of creating containing blocks for fixed-pos descendants etc, so you'd need to have `zoom` but somehow not parse `0` or `1`, or have different containing-block behavior for those values, which is just madness.

The issue with `zoom` as a property vs. Command-+ zoom is that `zoom` doesn't change the meaning of a CSS pixel, while Command-+ effectively does. So given Command-+ is global, all the coordinate spaces end up making sense.

But `zoom` needs to get undone on a bunch of APIs (otherwise things like `div.style.width = getComputedStyle(div).width` don't roundtrip), and I don't think it can be made to work nicely with things that cross zoom levels / are positioned: It effectively makes the meaning of a CSS pixel different based on each element, which means you can't really make sense of coordinates that cross differently-zoomed subtrees...

**Comment by karlcow** [comment]
I have started to experiment with a build deactivating CSS Zoom in WebKit. To see the impact and the extent of breakages. It probably creates other difficulties. 


The [bug at Mozilla for CSS Zoom](https://bugzilla.mozilla.org/show_bug.cgi?id=390936) lists some breakages. I will probably go through them to understand what is the current impact.

**Comment by karlcow** [comment]
* https://webcompat.com/issues/1118
  * Tokyo Metro - http://www.tokyometro.jp/sp/ They switched to a responsive design. 
  * Mobile
  * zoom is used but only with the form `*zoom: 1;` or `c.zoom = 1` and it doesn't break in Firefox. 
  * It doesn't have code targeting anymore Safari. 
* https://webcompat.com/issues/952
  * Circle K Sunkus brand has disappeared since 2018, including their websites.
  * Mobile
* https://webcompat.com/issues/1551
  * Tumblr theme. they removed the offending code in http://leftoversalad.tumblr.com/post/126724812097/programming-languages-personified
  * Mobile
  * The only CSS zoom instances are on the form of `t.style.zoom = 1`
* https://webcompat.com/issues/2103
  * another Tumblr. http://oliviawhen.tumblr.com/post/136358485941/i-did-some-physical-therapy-for-my-wrist-this-year
  * Mobile
  * They removed the offending zoom 
* https://webcompat.com/issues/3215
  * https://www.init.de/de
  * Mobile
  * They removed the zoom
* https://webcompat.com/issues/3789
  * https://weathernews.jp/web910/
  * Mobile/Tablet
  * They still use zoom in [one of their scripts](https://flux-cdn.com/client/weathernews/flux_weathernews_SP_AS_TM.min.js), but that seems related only to a part of the code about font-preferences.  `I() ? o.style.zoom = "" + 1 / n.devicePixelRatio : x() && (o.style.zoom = "reset");`
* https://webcompat.com/issues/7900
  * http://www.quikr.com/Escrow/nationwide/bazaar
  * Mobile
  * Removed CSS zoom
* https://webcompat.com/issues/16456
  * http://newpost.gr/
  * Mobile
  * Initial issue is gone. 
  * using also probably the same library than a previous site for fontPreferences `X() ? i.style.zoom = "".concat(1 / o.devicePixelRatio) : x() && (i.style.zoom = "reset");`. ah coming from `fingerprints`, so probably non sensical for layout.
* 🔴 https://github.com/webcompat/web-bugs/issues/101298
  * https://www.seedr.cc/ 
  * desktop
  * The login widget on the right side doesn't show all options. ![Screenshot 2023-05-02 at 12 33 21](https://user-images.githubusercontent.com/505230/235574102-15b183ca-a803-492f-86e4-5fd6fa649afe.png)
  * but they seem to use it on many places elsewhere with different values.
* 🔴 https://github.com/webcompat/web-bugs/issues/75053
  * https://bonk.io
  * desktop 
  * They use zoom at a couple of places. in their code. both css and html. ![Screenshot 2023-05-02 at 12 43 37](https://user-images.githubusercontent.com/505230/235574897-14da31a2-5278-483a-8d17-036a973967c6.png)
  * it creates layout issues.
* 🔴 https://github.com/webcompat/web-bugs/issues/80401 
  * http://ask8ball.net
  * Desktop
  * Layout broken ![Screenshot 2023-05-02 at 12 46 33](https://user-images.githubusercontent.com/505230/235575172-07809b61-0e89-480a-b797-b2c2872ab5a9.png)
  *  This is an interesting case because they added `zoom: 0.75; -moz-transform: scale(0.75);` in the hope to fix it for Firefox. It changes the size of the ball for example, but doesn't fix it completely. But deactivating `zoom` makes it even worse in WebKit (top right of the screenshot).
*  🔴 https://webcompat.com/issues/85044
  * https://salah.com
  * Desktop
  * Layout slightly modified. The text is a bit too big. 
  * They use zoom alone without trying to fix it for Firefox
* https://webcompat.com/issues/70232
  * https://dashingdon.com/play/wildelight/mind-blind/mygame/
  * Desktop/Mobile
  * I have the feeling they fixed it with a combination of zoom and transforms.
  * The zoom is set through JS on the body element. which is the simplest case to fix with transforms.
* https://webcompat.com/issues/67804
  * they got rid of it.
* https://github.com/webcompat/web-bugs/issues/47748
  * FIXED. but as you [can read another site](https://github.com/webcompat/web-bugs/issues/47748#issuecomment-611569325) which had a strategy of MozTransform + zoom, not fixing things.        
* https://github.com/webcompat/web-bugs/issues/4070
  * https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/OOP_ObjC/Introduction/Introduction.html
  * Still using zoom in the docs. but the initial issue with the button has probably been fixed. Not sure to double check. 
* 🔴 https://webcompat.com/issues/38470
  * https://mori-m-foundation.or.jp/english/ius2/gpci2/ 
  * Mobile
  * This one has a weird combination of UA sniffing and zoom. which applies only to Android. So to Firefox and Chrome.
```js
// iPhone
if(navigator.userAgent.indexOf('iPhone') != -1){
	document.write(
		'<meta name="viewport" content="width=640, user-scalable=no, maximum-scale=1.0" />',
		'<link rel="stylesheet" type="text/css" href="/css/sp_base.css" />',
		'<link rel="stylesheet" type="text/css" href="/css/sp_ius_gpci2022.css" />'
	);
}
// Android
else if(navigator.userAgent.indexOf('Android') != -1){
	document.write(
		'<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi" />',
		'<link rel="stylesheet" type="text/css" href="/css/sp_base.css" />',
		'<link rel="stylesheet" type="text/css" href="/css/sp_ius_gpci2022.css" />'
	);
	$("html").css("zoom" , $(window).width()/640 );
	$(window).bind('resize load', function(){
		$("html").css("zoom" , $(window).width()/640 );
	});
}
// PC
else{
	document.write(
		'<meta name="viewport" content="width=1200, user-scalable=yes" />',
		'<link rel="stylesheet" type="text/css" href="/css/base.css" />',
		'<link rel="stylesheet" type="text/css" href="/css/ius_gpci2022.css" />'
	);
}
```
* 🔴 https://webcompat.com/issues/34310
  * https://game.granbluefantasy.jp
  * Mobile
  * still using zoom with a combination of deviceRatio: `a.style.zoom = 1 / window.deviceRatio`

**Comment by karlcow** [comment]
**Just on the Web front** 

* Removing CSS Zoom would definitely break stuff online in terms of layout for both Chrome and Safari (or any browsers relying on Blink or WebKit).
* A lot of the previous bug reports have been fixed because of the wonderful outreach work of the Mozilla webcompat team.
* The issue could be mitigated for WebKit with Quirks on a site by site case by enabling CSS Zoom just for these sites. It doesn't clean up the code.  
* It would not solve legacy websites for Firefox, and it's difficult to solve it for them with site Interventions (except in the easy case of css zoom defined on the `html` or `body` elements) 
* Note that the breakage will be worse for Blink/WebKit for websites who tried to mitigate successfully with `MozTransform` + `MozTransformOrigin`.


PS: There's probably a lot of things which are not necessary visible right away, such as extensions.

**Comment by karlcow** [comment]
Another thing, Firefox sees only the case of websites which have been designed carelessly for Firefox, but not the cases where user agent sniffing is used for enabling css zoom. These would break only on Blink and WebKit.

**Comment by voxpelli** [comment]
Reminder that `zoom: 1` was a trick to trigger `hasLayout` in IE 7 and lower, so the existence of `zoom: 1` in pages is likely to be a remain from that era.

See eg: https://stackoverflow.com/a/6287038/20667

Hence `zoom: 1` is often not really relevant

**Comment by demike** [comment]
Industrial html5 applications are often optimized for touch devices ( big input elements ... )
Using `zoom` globally for desktop usage is often the only way to consistently scale the application.

Yes you could to that with i.e. 'rem'. 
But doing so you rely on implementation details of third party libraries ( they might not scale)

Think of browser based digital twins ...

**Comment by zcorpan** [comment]
@demike use cases for `zoom` is probably better to comment in https://github.com/w3c/csswg-drafts/issues/5623

**Comment by karlcow** [comment]
See https://github.com/w3c/csswg-drafts/issues/5623#issuecomment-1646125737

> The CSS Working Group just discussed `` Revisiting standardization of the `zoom` property ``, and agreed to the following:
> 
>     * `RESOLVED: add "zoom" as a real interoperable thing`
> 
>     * `RESOLVED: Add the zoom property to the device adaptation / viewport spec`

**Comment by smfr** [comment]
Based on the CSS WG resolution, I think we can close this.

**Comment by annevk** [comment]
Given @chrishtr wrote https://github.com/w3c/csswg-drafts/issues/5623#issuecomment-1644208565 himself let's close this as "proposal withdrawn".

**Comment by Buggem** [comment]
👎
