### ISSUE TITLE
improved styling of <details> and <summary> elements

### ISSUE THREAD

**Issue by dbaron** [WebKit/standards-positions#351]
### WebKittens

@annevk

### Title of the spec

improved styling of `<details>` and `<summary>` elements

### URL to the spec

Not a single spec, but a set of changes initially discussed in https://github.com/openui/open-ui/issues/744 and now moved to https://github.com/w3c/csswg-drafts/issues/9879 and https://github.com/whatwg/html/pull/10265 for the parts that belong in CSS and HTML respectively.

### Explainer URL

https://github.com/dbaron/details-styling

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/TBD

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1027

### Description

This is a proposal to add some features to both CSS and HTML (and additional precision to HTML) to make the `details` and `summary` elements more easily styleable by authors.

**Comment by karlcow** [comment]
Related to this on bugs.webkit.org side
https://bugs.webkit.org/show_bug.cgi?id=252223
https://bugs.webkit.org/showdependencytree.cgi?id=252223&hide_resolved=1

**Comment by annevk** [comment]
Making these elements better stylable makes a lot of sense. I suggest we resolve this as "position: support" one week from now.

I left these comments in the course of my review:

- `::details-content` vs `display: contents` might make them hard to remember, but that's probably a lost cause.
- If the text is generated by the user agent, it should probably adhere to the language of the node rather than the end user's chosen language. But that's an existing issue and can be follow-up.
