### ISSUE TITLE
Curve25519 in WebCrypto 

### ISSUE THREAD

**Issue by javifernandez** [WebKit/standards-positions#67]
## Request for position on an emerging web specification

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: Curve25519 in WebCrypto
* Spec URL: https://wicg.github.io/webcrypto-secure-curves/
* GitHub repository: https://github.com/WICG/webcrypto-secure-curves
* Issue Tracker:  https://github.com/WICG/webcrypto-secure-curves/issues
* Explainer: https://github.com/WICG/webcrypto-secure-curves/blob/main/explainer.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/466
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/271

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=245778
* Radar: 

### Anything else we need to know

This proposal tries to address the problems caused by the lack of in-browser implementations of safe curves by adding support for Curve25519 and Curve448 algorithms in the Web Cryptography API, namely the signature algorithms [Ed25519 and Ed448](https://datatracker.ietf.org/doc/html/rfc8032), and the key agreement algorithms [X25519 and X448](https://tools.ietf.org/html/rfc7748).

See the WICG [issue](https://github.com/WICG/proposals/issues/46) for details.

**Comment by othermaciej** [comment]
It this going to be proposed to WebAppSec (which owns the Web Crypto API)? Why is a separate WICG repo?

**Comment by othermaciej** [comment]
(To my knowledge this is technically a good idea but it would be nice to get this in a proper standards-track venue).

**Comment by annevk** [comment]
@othermaciej it seems that they did the drafting in WICG and as per https://github.com/w3c/webcrypto/issues/196 would move it into the WebAppSec draft if there's browser implementer support. I suspect it's done that way because there's also non-browser implementers, but not entirely sure. @twiss might be able to tell us.

**Comment by twiss** [comment]
Hey :wave: The reason it's in WICG is because [the new WebAppSec charter](https://www.w3.org/2022/06/webappsec-charter-2022.html) says that

> The WG may adopt well-supported proposals from incubation for maintenance of the Web Cryptography API.

and AFAIU the intention behind that was that new proposals would happen in the WICG, and mostly be discussed there. Nevertheless, there was also some discussion in the WebAppSec group, e.g. at TPAC, the minutes of which are [here](https://github.com/w3c/webappsec/blob/main/meetings/2022/2022-09-12-TPAC-minutes-1.md#web-crypto).

In fact, as far as I understood from @johnwilander (in that conversation), someone at Apple (not sure who) is already working on implementing Curve25519 :)

> The WICG repo creation issue says WebAppSec rejected adding these algorithms to Web Crypto, but doesn't cite a source for their rejection. And neither the issue nor the explainer seem to explain the reasoning for WebAppSec's rejection, which seems like it may be relevant.

So yeah, it was discussed in WebAppSec and it wasn't rejected there, I'm not sure where or how I raised that impression, but once it's well-supported, these algorithms should be added to the main Web Crypto API specification.

---

While I have your attention, I'd like to raise the main open issue in the WICG repo, https://github.com/WICG/webcrypto-secure-curves/issues/10, which is about error handling, specifically for small-order elements, and whether we want to do so during key import or key derivation (in the case of X25519 and X448), for example. There is an associated PR switching from the latter to the former, with a bunch of discussion; it would be great to get your input on this point.

**Comment by othermaciej** [comment]
Looking again, and I think it's a late-night misreading on my part. the WICF proposal issue only said that Web Crypto doesn't support safe curves; it doesn't say there was explicit refusal to add them.

**Comment by othermaciej** [comment]
@twiss 
> While I have your attention, I'd like to raise the main open issue in the WICG repo, https://github.com/WICG/webcrypto-secure-curves/issues/10, which is about error handling, specifically for small-order elements, and whether we want to do so during key import or key derivation (in the case of X25519 and X448), for example. There is an associated PR switching from the latter to the former, with a bunch of discussion; it would be great to get your input on this point.

If you need a WebKit view on this (it's ok for the requests to be about issues, not necessarily just whole specs) please file a separate standards-positions issue so it doesn't get lost.

**Comment by othermaciej** [comment]
`concerns: venue` label was added because this is a WICG spec patching/extending a WebAppSec spec. Seems this is understood though and the progression path is to move to WebAppSec if there is browser interest.

**Comment by annevk** [comment]
Chatting with colleagues it seems everyone thinks this is a reasonable addition. As such I suggest we label this "position: support" in 7 days.

Hopefully that'll also help resolve the venue concern discussed above.

**Comment by twiss** [comment]
> If you need a WebKit view on this (it's ok for the requests to be about issues, not necessarily just whole specs) please file a separate standards-positions issue so it doesn't get lost.

Apologies for the delay, done now: https://github.com/WebKit/standards-positions/issues/82. Thanks!

**Comment by hober** [comment]
Closing as we've identified our position.
