### ISSUE TITLE
CSS Nesting Module Level 1

### ISSUE THREAD

**Issue by lilles** [WebKit/standards-positions#69]
### Information about the spec

* Spec Title: CSS Nesting Module Level 1
* Spec URL: https://drafts.csswg.org/css-nesting-1/
* GitHub repository: https://github.com/w3c/csswg-drafts

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/695

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=223497

### Anything else we need to know

Add the ability to nest CSS style rules inside other style rules, combining selectors from the outer with the inner rule for increasing modularity and maintainability of style sheets.

**Comment by anttijk** [comment]
I'm very concerned about the CSSOM portion of the spec. Adding children to CSSStyleRule would substantially increase implementation complexity of this rarely used corner of CSS. Current WebKit implementation of rule matching is fairly tightly tied to the internal representation of StyleRule. Now we would likely need to add a level of abstraction where the nesting is flattened and switching the rule matching to run against this new structure. There would need to be significant amount of code to keep the CSSOM and the new flattened representation in sync.

Since CSSOM is mutable this would require a large testing matrix for verifying that complex nested mutations work and invalidate correctly.

Also CSSStyleRule with children seems rather confusing API from the developer perspective.

Considering how rarely used stylesheet CSSOM is, I'm doubtful the implementation and testing complexity can be justified. Maybe the feature can be recast to be purely a parse time transformation (similar to CSS preprocessors) that desugars to regular style rules and does not roundtrip via CSSOM? Inspector support would likely then be limited too.

**Comment by astearns** [comment]
@anttijk could you or one of your colleagues open an issue in the [CSSWG repo](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-nesting+cssom+is%3Aopen) on this concern? As far as I can tell we have not considered alternatives to adding children to CSSStyleRules yet.

**Comment by anttijk** [comment]
The current draft has reduced the complexity compared to one I reviewed by not turning CSSStyleRule into a group rule anymore.

**Comment by annevk** [comment]
Colleagues and I discussed this further and would like to label this as "position: support" on January 6 (some additional time to account for the holidays).

**Comment by hober** [comment]
Closing as we've identified our position.
