### ISSUE TITLE
CSS `initial-letter` property

### ISSUE THREAD

**Issue by yosinch** [WebKit/standards-positions#94]
### Information about the spec

* Spec Title: CSS Inline Layout Module Level 3
* Spec URL:  https://drafts.csswg.org/css-inline/#initial-letter-styling
* GitHub repository: https://github.com/w3c/csswg-drafts

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1273019

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=229090

### Anything else we need to know
Blink plans to this property.  [Intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/zV9K3hdBwDM/m/Fz1H_myjBQAJ).

**Comment by hober** [comment]
We've been pretty enthusiastic about this property in the past, and are shipping an implementation, though I don't remember offhand if it's still prefixed or how closely it matches the current spec. I suspect we should mark this as `position: support`, but I'll defer to folk who have been more closely tracking the CSSWG than I've been of late. cc @jensimmons @litherum

**Comment by jensimmons** [comment]
I would expect us to support this, since we invented it and shipped an experimental version behind a `-webkit` prefix in 2015.

The current WebKit implementation: 
- does still require a `-webkit` prefix
- does not support web fonts (only system fonts)
- does not include support for `initial-letter-align`
- does not include support for `initial-letter-wrap` 
- may need refinement of sinking, `raise`, `drop`; how initial letters interact with floats, writing modes, padding and margins; how glyphs align internationally; etc — since these details were all specified after our original implementation 
- may also need to update how many/which characters are included in `::first-letter`

**Comment by hober** [comment]
After talking with colleagues about this today, we're generally supportive of this and will mark this 'support' in one week unless there are objections.
